version: "2"

# Docker compose for quickstart (demo on local environment)

services:
  postgres:
    image: postgres:11.6
    ports:
      - "5432:5432"
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_CONFIGURATION=LocalDemo
    build: ./
    command: >
      bash -c "python /code/docker/wait.py postgres &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8010:8000"
    depends_on:
      - postgres
