site_name: menuratings
site_description: Sample django rest app.
repo_url: https://github.com/andriusbalcikonis/django-rest-sample-app
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/andriusbalcikonis">andriusbalcikonis</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: "index.md"
  - API:
      - Authentication: "api/authentication.md"
      - Users: "api/users.md"
theme: readthedocs
