# Generated by Django 3.0.7 on 2020-06-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mr", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="menu", unique_together={("date", "restaurant")},
        ),
    ]
