version: "2"

services:
  postgres:
    image: postgres:11.6
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.19
    container_name: pgadm
    restart: always
    ports:
      - "8001:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
